[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 11

[general]
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]
